package com.hotelreservation.service;

import com.hotelreservation.model.Staff;
import com.hotelreservation.model.StaffLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;

public class LogoutService {
    private static final Logger logger = LoggerFactory.getLogger(LogoutService.class);
    private final StaffLogService staffLogService = new StaffLogService();

    /**
     * Handles the logout process for a staff member.
     * 
     * @param staff The staff member logging out
     * @return true if logout was successful, false otherwise
     */
    public boolean logout(Staff staff) {
        try {
            // Log the logout action
            StaffLog logEntry = new StaffLog(
                null, // ID will be generated by database
                staff.getStaffId(),
                "Logout",
                "User logged out",
                LocalDateTime.now()
            );
            staffLogService.addLog(logEntry);
            
            logger.info("Staff member {} logged out successfully", staff.getStaffId());
            return true;
        } catch (Exception e) {
            logger.error("Error during logout for staff: " + staff.getStaffId(), e);
            return false;
        }
    }
}
